

package test.tests;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link test.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("src/testData/cases")
@TestDataPath("$PROJECT_ROOT")
public class CasesTestGenerated extends BaseCompilerTest {
  private void run(String fileName) {
    runTest("src/testData/cases/" + fileName);
  }

  @Test
  public void testAllFilesPresentInCases() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/testData/cases"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("firRead.kt")
  public void testFirRead() {
    run("firRead.kt");
  }

  @Test
  @TestMetadata("firWrite.kt")
  public void testFirWrite() {
    run("firWrite.kt");
  }

  @Test
  @TestMetadata("firWriteIrRead.kt")
  public void testFirWriteIrRead() {
    run("firWriteIrRead.kt");
  }

  @Test
  @TestMetadata("firWriteReadEquality.kt")
  public void testFirWriteReadEquality() {
    run("firWriteReadEquality.kt");
  }

  @Test
  @TestMetadata("irRead.kt")
  public void testIrRead() {
    run("irRead.kt");
  }

  @Test
  @TestMetadata("irWrite.kt")
  public void testIrWrite() {
    run("irWrite.kt");
  }

  @Test
  @TestMetadata("irWriteReadEquality.kt")
  public void testIrWriteReadEquality() {
    run("irWriteReadEquality.kt");
  }
}
