

package dev.rnett.lattice.tests;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link dev.rnett.lattice.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("src/testData/errors")
@TestDataPath("$PROJECT_ROOT")
public class ErrorsTestGenerated extends BaseDiagnosticCompilerTest {
  @Test
  public void testAllFilesPresentInErrors() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/testData/errors"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("AnnotationExportDuplicates.kt")
  public void testAnnotationExportDuplicates() {
    runTest("src/testData/errors/AnnotationExportDuplicates.kt");
  }

  @Test
  @TestMetadata("AnnotationExportNonAnnotation.kt")
  public void testAnnotationExportNonAnnotation() {
    runTest("src/testData/errors/AnnotationExportNonAnnotation.kt");
  }

  @Test
  @TestMetadata("AnnotationExportNonExportedParam.kt")
  public void testAnnotationExportNonExportedParam() {
    runTest("src/testData/errors/AnnotationExportNonExportedParam.kt");
  }

  @Test
  @TestMetadata("InternalDeclarations.kt")
  public void testInternalDeclarations() {
    runTest("src/testData/errors/InternalDeclarations.kt");
  }

  @Test
  @TestMetadata("LocalDeclarations.kt")
  public void testLocalDeclarations() {
    runTest("src/testData/errors/LocalDeclarations.kt");
  }

  @Test
  @TestMetadata("OKProtectedDeclarations.kt")
  public void testOKProtectedDeclarations() {
    runTest("src/testData/errors/OKProtectedDeclarations.kt");
  }

  @Test
  @TestMetadata("OKPublicDeclarations.kt")
  public void testOKPublicDeclarations() {
    runTest("src/testData/errors/OKPublicDeclarations.kt");
  }

  @Test
  @TestMetadata("OKPublishedAPIDeclarations.kt")
  public void testOKPublishedAPIDeclarations() {
    runTest("src/testData/errors/OKPublishedAPIDeclarations.kt");
  }

  @Test
  @TestMetadata("ParentsNotMarked.kt")
  public void testParentsNotMarked() {
    runTest("src/testData/errors/ParentsNotMarked.kt");
  }

  @Test
  @TestMetadata("PrivateDeclarations.kt")
  public void testPrivateDeclarations() {
    runTest("src/testData/errors/PrivateDeclarations.kt");
  }
}
