

package dev.rnett.lattice.tests;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link dev.rnett.lattice.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-plugin/src/testData/export")
@TestDataPath("$PROJECT_ROOT")
public class ExportTestGenerated extends BaseDiagnosticCompilerTest {
  @Test
  public void testAllFilesPresentInExport() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/src/testData/export"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("Annotation.kt")
  public void testAnnotation() {
    runTest("compiler-plugin/src/testData/export/Annotation.kt");
  }

  @Test
  @TestMetadata("Class.kt")
  public void testClass() {
    runTest("compiler-plugin/src/testData/export/Class.kt");
  }

  @Test
  @TestMetadata("ClassMembers.kt")
  public void testClassMembers() {
    runTest("compiler-plugin/src/testData/export/ClassMembers.kt");
  }

  @Test
  @TestMetadata("ContextParameters.kt")
  public void testContextParameters() {
    runTest("compiler-plugin/src/testData/export/ContextParameters.kt");
  }

  @Test
  @TestMetadata("DispatchReceiver.kt")
  public void testDispatchReceiver() {
    runTest("compiler-plugin/src/testData/export/DispatchReceiver.kt");
  }

  @Test
  @TestMetadata("EnumEntry.kt")
  public void testEnumEntry() {
    runTest("compiler-plugin/src/testData/export/EnumEntry.kt");
  }

  @Test
  @TestMetadata("ExportObject.kt")
  public void testExportObject() {
    runTest("compiler-plugin/src/testData/export/ExportObject.kt");
  }

  @Test
  @TestMetadata("ExtensionReceiver.kt")
  public void testExtensionReceiver() {
    runTest("compiler-plugin/src/testData/export/ExtensionReceiver.kt");
  }

  @Test
  @TestMetadata("Interface.kt")
  public void testInterface() {
    runTest("compiler-plugin/src/testData/export/Interface.kt");
  }

  @Test
  @TestMetadata("NestedClass.kt")
  public void testNestedClass() {
    runTest("compiler-plugin/src/testData/export/NestedClass.kt");
  }

  @Test
  @TestMetadata("TopLevelMembers.kt")
  public void testTopLevelMembers() {
    runTest("compiler-plugin/src/testData/export/TopLevelMembers.kt");
  }

  @Test
  @TestMetadata("TypeParameters.kt")
  public void testTypeParameters() {
    runTest("compiler-plugin/src/testData/export/TypeParameters.kt");
  }

  @Test
  @TestMetadata("ValueParameters.kt")
  public void testValueParameters() {
    runTest("compiler-plugin/src/testData/export/ValueParameters.kt");
  }
}
