

package dev.rnett.lattice.tests;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link dev.rnett.lattice.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("src/testData/reference/export")
@TestDataPath("$PROJECT_ROOT")
public class ReferenceExportTestGenerated extends BaseDiagnosticCompilerTest {
  @Test
  public void testAllFilesPresentInExport() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/testData/reference/export"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("ExportAnnotation.kt")
  public void testExportAnnotation() {
    runTest("src/testData/reference/export/ExportAnnotation.kt");
  }

  @Test
  @TestMetadata("ExportClass.kt")
  public void testExportClass() {
    runTest("src/testData/reference/export/ExportClass.kt");
  }

  @Test
  @TestMetadata("ExportClassWithTypeParams.kt")
  public void testExportClassWithTypeParams() {
    runTest("src/testData/reference/export/ExportClassWithTypeParams.kt");
  }

  @Test
  @TestMetadata("ExportEnumEntries.kt")
  public void testExportEnumEntries() {
    runTest("src/testData/reference/export/ExportEnumEntries.kt");
  }

  @Test
  @TestMetadata("ExportFunction.kt")
  public void testExportFunction() {
    runTest("src/testData/reference/export/ExportFunction.kt");
  }

  @Test
  @TestMetadata("ExportFunctionWithParameters.kt")
  public void testExportFunctionWithParameters() {
    runTest("src/testData/reference/export/ExportFunctionWithParameters.kt");
  }

  @Test
  @TestMetadata("ExportProperty.kt")
  public void testExportProperty() {
    runTest("src/testData/reference/export/ExportProperty.kt");
  }

  @Test
  @TestMetadata("ExportPropertyWithParameters.kt")
  public void testExportPropertyWithParameters() {
    runTest("src/testData/reference/export/ExportPropertyWithParameters.kt");
  }

  @Test
  @TestMetadata("ExportReferencedFunction.kt")
  public void testExportReferencedFunction() {
    runTest("src/testData/reference/export/ExportReferencedFunction.kt");
  }

  @Test
  @TestMetadata("ExportReferencedFunctionWithParameters.kt")
  public void testExportReferencedFunctionWithParameters() {
    runTest("src/testData/reference/export/ExportReferencedFunctionWithParameters.kt");
  }

  @Test
  @TestMetadata("ExportReferencedProperty.kt")
  public void testExportReferencedProperty() {
    runTest("src/testData/reference/export/ExportReferencedProperty.kt");
  }
}
